version: "3.7"
services:
  train-mleng:
    image: ${MLENG_IMG}
    build:
      context: .
      dockerfile: "service/train_mleng/Dockerfile"
      args:
        - MODEL_VERSION=${MODEL_VER}
        - BUCKET_DATA=${BUCKET_DATA_GCP}
        - BUCKET_CONFIG=${BUCKET_CONFIG_GCP}
        - BUCKET_MODEL=${BUCKET_MODEL_GCP}