learning_rate:
  - 0.01
  - 0.05
  - 0.1
  - 0.5
n_estimators:
  - 10
  - 20
  - 50
  - 100
  - 200
  - 300
  - 500
max_depth:
  - 5
  - 10
  - 20
  - 50
  - 100
  - 200
  - 500
gamma:
  - 0.1
  - 0.2
  - 0.5
  - 0.8
  - 1
reg_alpha:
  - 0.1
  - 0.5
  - 0.6
  - 0.8
  - 1
reg_ramma:
  - 0.1
  - 0.5
  - 0.6
  - 0.8
  - 1
